name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: List repository contents
      run: |
        echo "Root directory contents:"
        ls -la
        echo "Frontend directory contents:"
        ls -la frontend/
        
    - name: Check package.json
      run: |
        echo "Checking if package.json exists:"
        cat frontend/package.json
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
      working-directory: ./frontend
      
    - name: Build React app
      run: |
        echo "Building React app..."
        npm run build
      working-directory: ./frontend
      
    - name: Check build output
      run: |
        echo "Build directory contents:"
        ls -la frontend/build/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './frontend/build'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
